### ISSUE TITLE
Python3 bindings

### ISSUE THREAD

**Issue by WPettersson** [regina-normal/regina#1]
I imagine the python3 versions of the bindings should install and be usable just fine if you link to the right interpreter and libraries, but it'd be good to

1. allow python2 and python3 bindings to be installed side-by-side, and
2. actually test the python3 bindings separately in this case.

**Comment by baburton** [comment]
This should all be good now - the build now works against either python2 or python3. The modules can be installed side-by-side (since they live within the python site-packages directories), though the cmake build system does not support building both modules under a single cmake configuration.
