### ISSUE TITLE
Cut along almost normal surfaces

### ISSUE THREAD

**Issue by baburton** [regina-normal/regina#17]
A user has asked for the ability to cut along almost normal surfaces (currently only *normal* surfaces are supported).

**Comment by bobbycyiii** [comment]
This issue is subsumed by #33. If ``S`` is a surface in ``T``, and ``T'``is a triangulation of the same space, and ``S`` is normal in ``T'``, then to cut ``T`` along ``S``, just cut ``T'`` along ``S`` instead.

**Comment by baburton** [comment]
Cutting along almost normal surfaces is now possible with Regina 7.1. - Ben.
