### ISSUE TITLE
Generic implementation of kth homology

### ISSUE THREAD

**Issue by baburton** [regina-normal/regina#19]
Currently only H_1 is generic, and its implementation is specialised.  Presumably a generic H_k implementation would use the chain complex machinery from engine/algebra/.

**Comment by delooper** [comment]
The code in NCellularData could easily be rewritten to be generic.  Right now it's implemented for 3-manifolds and 4-manifolds piecewise, due to Regina's history.  But it won't be hard to make that generic once NCellularData is up and running again.

**Comment by baburton** [comment]
Oh, just spotted this. A generic Triangulation<dim>::homology<k>() was implemented in regina 7.0. - Ben.
