### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by bobbycyiii** [regina-normal/regina#44]
I cloned the GitHub repo, installed the prerequisites (except for MPI, Doxygen, and xsltproc), and ran CMake. CMake finished just fine. Running make in the same directory compiled until trying to build ..../angle/anglestructure.cpp.o, which fails with the following error:

In file included from /home/robert/Programs/regina/engine/triangulation/dim3/triangulation3.h:3113:0,
                 from /home/robert/Programs/regina/engine/triangulation/dim3.h:45,
                 from /home/robert/Programs/regina/engine/angle/anglestructure.cpp:35:
/home/robert/Programs/regina/engine/triangulation/dim3/tetrahedron3.h:123:60: error: specialization of ‘template<int dim> regina::Face<dim, 1>* regina::detail::SimplexBase<dim>::edge(int, int) const’ in different namespace [-fpermissive]
 inline Edge<3>* detail::SimplexBase<3>::edge(int i, int j) const {
                                                            ^~~~~
In file included from /home/robert/Programs/regina/engine/triangulation/generic/simplex.h:46:0,
                 from /home/robert/Programs/regina/engine/triangulation/detail/triangulation.h:57,
                 from /home/robert/Programs/regina/engine/triangulation/generic/triangulation.h:212,
                 from /home/robert/Programs/regina/engine/triangulation/dim3/triangulation3.h:55,
                 from /home/robert/Programs/regina/engine/triangulation/dim3.h:45,
                 from /home/robert/Programs/regina/engine/angle/anglestructure.cpp:35:
/home/robert/Programs/regina/engine/triangulation/detail/simplex.h:446:23: error:   from definition of ‘template<int dim> regina::Face<dim, 1>* regina::detail::SimplexBase<dim>::edge(int, int) const’ [-fpermissive]
         Face<dim, 1>* edge(int i, int j) const {
                       ^~~~
engine/CMakeFiles/regina-engine.dir/build.make:206: recipe for target 'engine/CMakeFiles/regina-engine.dir/angle/anglestructure.cpp.o' failed
make[2]: *** [engine/CMakeFiles/regina-engine.dir/angle/anglestructure.cpp.o] Error 1
CMakeFiles/Makefile2:162: recipe for target 'engine/CMakeFiles/regina-engine.dir/all' failed
make[1]: *** [engine/CMakeFiles/regina-engine.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by delooper** [comment]
Hi Robert, 
Which version of gcc are you compiling with?  Type "gcc --version" into your command line and paste the output here.  I suspect you are using an older version that has trouble with Regina's template code.  But perhaps I'm wrong and Ben or William will come along and spot the problem later.

**Comment by bobbycyiii** [comment]
Hi Ryan,

That seems to have fixed the problem. Thank you!

I was indeed using an older version, viz. version 6.3.0 20170516.
Updating gcc and g++ to version 8 has resolved this issue.
Best regards,
Robert


On Fri, Sep 7, 2018, at 10:17, Ryan Budney wrote:
> Hi Robert,
>  Which version of gcc are you compiling with?  Type "gcc --version"
>  into your command line and paste the output here.  I suspect you are
>  using an older version that has trouble with Regina's template code.
>  But perhaps I'm wrong and Ben or William will come along and spot the
>  problem later.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/regina-normal/regina/issues/44#issuecomment-419507522
