### ISSUE TITLE
custom Python site-packages directory

### ISSUE THREAD

**Issue by beew** [regina-normal/regina#46]
Hello,

I am wondering if there is a way to specify Python site-packages directory since I would like to install Regina in $HOME, instead of /usr/local, so I would like to install the python module in $HOME/.local/lib/python2.7/site-packages instead of the default /usr/lib/python2.7/dist-packages. I could set -DCMAKE_INSTALL_PREFIX to $HOME/regina for regina but that doesn't change the Python site-packages directory.

Thanks.

OS is Ubuntu 16.04 (gcc-8.2 so building is no problem)

**Comment by WPettersson** [comment]
Are you using virtual environments for this? If so, it should just work as we get the site-packages directory by running 

```python
import distutils.sysconfig
print(distutils.sysconfig.get_python_lib(True))
```

Test running that snipped within your virtual environment, and see if it prints out $HOME/.local/lib/python2.7/site-packages

**Comment by beew** [comment]
No, not using virtual environment. But I can adjust PYTHONPATH and PYTHON_BASE in .bashrc or .profile

**Comment by WPettersson** [comment]
I don't know PYTHON_BASE, but I don't think this will be something we will be supporting. If you're comfortable enough supporting your own configuration for Python module locations, you should be able to edit CMakeLists yourself to set the appropriate place to install them there, but we only support the method described above, using distutils.sysconfig to ensure that Python can find the modules.
