### ISSUE TITLE
6.1 deprecations

### ISSUE THREAD

**Issue by WPettersson** [regina-normal/regina#53]
Remove all the deprecations (i.e. nabeliangroup.h and other headers that unnecessarily begin with n, and corresponding typedefs).

**Comment by WPettersson** [comment]
I've pushed the majority of the changes required into the 6.0_deprecations branch (current head f10d43bd506e355fa297bbaeed8166437e235bc2). At least two things still remain though:
* Fix tests (the removed classes result in failed tests)
* Remove the MPI utilities

**Comment by WPettersson** [comment]
Tests should work (at fc376d372)

**Comment by WPettersson** [comment]
The rest of the MPI utilities, including references within man pages and those in utils/local/mpi, have been removed now.

**Comment by baburton** [comment]
FYI, I've gone over the 6.0_deprecations branch, put a couple of minor things back, and am happy for this to be merged into master.

Having said that, I'd like to do this for 6.1, not 6.0 (due to how recent the 6.0 prerelease was).

I'll do the merge once 6.0 proper is out. - b.

**Comment by baburton** [comment]
In the end this all happened with release 7.0; closing this now. - Ben.
