### ISSUE TITLE
6.0 alpha tests fail on armhf

### ISSUE THREAD

**Issue by xnox** [regina-normal/regina#58]
[armhf-cpp-test-fail.txt](https://github.com/regina-normal/regina/files/4716060/armhf-cpp-test-fail.txt)

I have access to arm64 & armhf to test things on.

And I think travis has access to arm64 too (which can be forced to compiler/run armhf code maybe?)

```
LinkTest::jones... ok.
LinkTest::homfly... 


50% tests passed, 1 tests failed out of 2

Total Test time (real) =  97.84 sec

The following tests FAILED:
          2 - cpp-test (SEGFAULT)
```

Note Ubuntu builders run arm64 kernel, and arm64 userspace, which then starts armhf container where the build & testing happens.

**Comment by baburton** [comment]
Hi - I found this issue also, and it is fixed with Regina 5.96 (just released). Confirmed that it works now on the Debian autobuilders. - Ben.
