### ISSUE TITLE
Polynomial-time splitting surface location

### ISSUE THREAD

**Issue by bobbycyiii** [regina-normal/regina#59]
Splitting surface location doesn't require a vertex-surface enumeration; it only requires what amounts to a sort of depth-first search through edges starting at only three edges of a triangle.

**Comment by WPettersson** [comment]
This is now merged into 6.0_pre, will close when we either release 6.0, or it gets back-ported.

**Comment by baburton** [comment]
Backported to master, will appear in the next release (5.97 or 6.0, whichever comes first). - Ben.
