### ISSUE TITLE
Linking with Python3 could be easier

### ISSUE THREAD

**Issue by bobbycyiii** [regina-normal/regina#60]
I found it awkward to get CMake to compile Regina with Python3. Adding a flag to the root CMakeLists.txt would help.

**Comment by bobbycyiii** [comment]
Ultimately this issue should be automatically taken care of by CMake. Since CMake 3.12 the findPythonInterp and findPythonLibs modules are [deprecated](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html). The docs say to use the [findPython](https://cmake.org/cmake/help/latest/module/FindPython.html#module:FindPython) module instead. I tried switching CMakeLists.txt (and examples/CMakeLists.txt) to use the newer module, but couldn't get Regina to compile this way.

**Comment by baburton** [comment]
Hi Robert,

> I found it awkward to get CMake to compile Regina with Python3. Adding a flag to the root CMakeLists.txt would help.

On my machine, I’m passing -DPYTHON_EXECUTABLE=/opt/sw/bin/python3 . Everything else it should be able to work out via the python executable.

(The question should not really be “which python version”, but “which python executable”, since some people have multiple installations of the same version of python and they need to be able to control which is used.)

- b.

**Comment by WPettersson** [comment]
I've been thinking about this, and I think that if we are looking at the python build process (updating to avoid deprecated findPythonInterp) then we might want to also consider some way of building and linking the python bindings against multiple python installs. Ideally this could be done without rebuilding the library each time. For instance, I currently have python 3.6, 3.7, 3.8 and 3.9 installed, and it'd be nice to be able to use regina in each setting.
One option is to compile all of regina for each version, and I think that's what would be required for distribution through services like pypi, but I don't know how to do that for a "typical" install (unless we want lots of copies of the regina library floating around).
Another option is to pass some sort of --use-system-regina flag to cmake. This would skip building the actual engine, but try to include it from `/usr/lib64` or similar, and pull headers from `/usr/include`. This would mean tweaking most of the python bindings to e.g. change includes from using quote marks to angle brackets

**Comment by baburton** [comment]
A note here: regina 5.96 (just released) now uses the FindPython module. On my macOS system, I'm passing -DPython_EXECUTABLE=/usr/bin/python versus -DPython_EXECUTABLE=/usr/bin/python3 and that's all I need to switch between the python2/python3 builds. Would be happy to hear if this kind of thing is working for you.

**Comment by bobbycyiii** [comment]
Artifact specification like -DPython_EXECUTABLE=... is available in CMake's FindPython module since version 16. Once I upgraded to the latest CMake version, this worked for me. Thank you, Ben!
