### ISSUE TITLE
Triangulation2 does not have fundamentalGroup method in Python interface

### ISSUE THREAD

**Issue by NathanDunfield** [regina-normal/regina#77]
In the Python interface for 7.0, trying to call the `fundamentalGroup` method for a `Triangulation2` results in an `AttributeError`.   However, that method is listed in [C++ docs](https://regina-normal.github.io/engine-docs/classregina_1_1Triangulation_3_012_01_4.html).

```
>>> import regina
>>> regina.versionString()
'7.0'
>>> hasattr(regina.Triangulation2, 'fundamentalGroup')
False
>>> hasattr(regina.Triangulation3, 'fundamentalGroup')
True
>>> hasattr(regina.Triangulation4, 'fundamentalGroup')
True
```
Observed in Linux and macOS.

**Comment by WPettersson** [comment]
Yup, it's missing from python for some reason. I'll wait to see if Ben has a reason for not having included it, but it's simple to add if it was just overlooked. I've pushed a branch that does re-add it, which can just be merged if that's the case.

**Comment by baburton** [comment]
Oh, snap. I just fixed this in master at the same time as William fixed it in this branch.

Nathan: if you need it now you can pull and rebuild; if not urgent, 7.1 is coming out this month anyway.

Will: thanks also. :)

**Comment by NathanDunfield** [comment]
Thanks to both for the quick fix!  I only came across this when writing a doctest for a script I was working on and thought `Example2.torus().fundamentalGroup()` would be an easy way to get a presentation for Z^2...

**Comment by baburton** [comment]
> I only came across this when writing a doctest for a script I was working on and thought Example2.torus().fundamentalGroup() would be an easy way to get a presentation for Z^2...

GroupPresentation does have a string-based constructor. You could try:

GroupPresentation(2, ['abAB’])

- b.
